server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 47.92.210.212
      port: 6379
      password: 123456
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
