server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
    # active: dev
  data:
    redis:
      host: 124.70.87.154
      port: 6379
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
    nacos:
      discovery:
        server-addr: 124.70.87.154:8848
