server:
  port: 8001
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  short-link:
    domain:
      default: my:8001
    stats:
      locale:
        amap-key: f440e8153ca04dd6b42399bcaf6ce99d
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 124.70.87.154
      port: 6379
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
